services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true # 方便我们读取

  CreditBundle\Command\:
    resource: '../../Command/'
  CreditBundle\Controller\:
    resource: '../../Controller/'
  CreditBundle\Procedure\:
    resource: '../../Procedure/'
  CreditBundle\Repository\:
    resource: '../../Repository/'
  CreditBundle\Service\:
    resource: '../../Service/'
  
  # AdminMenu 服务
  CreditBundle\AdminMenu: ~
